---
- name: Converge
  hosts: molecule_coturn:!molecule-coturn-stun-client
  become: yes

  vars:
    ansible_python_interpreter: python3

    coturn_log_level: INFO
    coturn_prometheus_enabled: true
    coturn_auth_mechanism: long-term
    coturn_users:
      - username: test
        password: test
    coturn_realm: test
    coturn_allowed_peer_ips:
      - 172.0.0.0/8
    coturn_listening_port: 12345
    coturn_alternative_listening_port: 54321

    consul_enabled: true

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
