---
name: Tests

on:
  push:
    tags:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip"
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Tox
        run: pip install tox

      - name: Cache Tox
        uses: actions/cache@v2
        with:
          path: ~/.tox
          key: "${{ runner.os }}-tox-{% raw %}${{ hashFiles('**/tox.ini') }}{% endraw %}"
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Install Tox
        run: pip install tox

      - name: Setup git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: "${{secrets.GIT_CREDENTIALS}}"

      - name: Run Tox
        run: tox

      - name: Mattermost notification
        if: ${{ failure() }}
        # https://github.com/marketplace/actions/slack-notify
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: "${{ secrets.MATTERMOST_WEBHOOK }}"
          SLACK_CHANNEL: "dev-failed-tests"
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/Octocat.png"
          SLACK_USERNAME: "GitHub Actions"
          SLACK_COLOR: "danger"
          SLACK_MESSAGE: "Ansible role test failed :nuke:'"
          SLACK_FOOTER: ""
